name: PlaceholderAPI Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    if: "!startsWith(github.event.head_commit.message, 'ci-skip')"

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin
        cache: gradle
          
    - name: Build artifacts
      run: ./gradlew build
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        path: placeholderapi/build/libs/*.jar
